name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: change_directory
      run: cd testCommon
    - name: pwd
      run: pwd
    - name: CppuTest on host
      run: make run
