name: C/C++ CI

on:
  push:
    branches: [ master ]
      runs-on: self-hosted

      steps:
      - run: make run
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init
    - name: autoreconf cppUTest
      run: autoreconf .. -i
      working-directory: ./cpputest/cpputest_build
    - name: configure cppUTest
      run: ../configure
      working-directory: ./cpputest/cpputest_build
    - name: build cppUTest
      run: make
      working-directory: ./cpputest/cpputest_build
    - name: CppuTest on host
      run: make run
      working-directory: ./testCommon
