name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init
    - name: autoreconf cppUTest
      run: autoreconf .. -i
      working-directory: ./cpputest/cpputest_build
    - name: configure cppUTest
      run: ../configure
      working-directory: ./cpputest/cpputest_build
    - name: build cppUTest
      run: make
      working-directory: ./cpputest/cpputest_build
    - name: CppuTest on host
      run: make run
      working-directory: ./testCommon
    - name: remove nodejs
      run: sudo rm -rf /usr/local/lib/nodejs
    - name: remove npm
      run: rm -rf ~/opt/npm
    - name: delete npm
      run: npm config delete prefix
    - name: remove npm from path
      run: export PATH=${PATH%:/${HOME}/opt/npm/bin}
    - name: install nvm
      run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
    - name: export new NVM dir
      run: export NVM_DIR="$HOME/.nvm"
    - name: load NVM
      run: "$NVM_DIR/nvm.sh"
    - name: load nvm bash completion
      run: "$NVM_DIR/bash_completion"
    - name: install latest node
      run: nvm install --lts node
    - name: switch to latest node
      run: nvm use node
    - name: install latest npm
      run: nvm install-latest-npm
    - name: install xpm
      run: npm install --global xpm@latest
    - name: install arm toolchain
      run: xpm install @gnu-mcu-eclipse/arm-none-eabi-gcc --global
