name: C/C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: "actions/checkout@v3"
    - name: checkout submodules
      run: git submodule update --init
    - name: autoreconf cppUTest
      run: autoreconf .. -i
      working-directory: ./cpputest/cpputest_build
    - name: configure cppUTest
      run: ../configure
      working-directory: ./cpputest/cpputest_build
    - name: build cppUTest
      run: make
      working-directory: ./cpputest/cpputest_build
    - name: CppuTest on host
      run:  make run
      working-directory: ./testCommon
    - name: Build for target
      run: make
    - name: Copy to HEX
      run: $GNU_ARM_TOOL_PATH/bin/arm-none-eabi-objcopy -Oihex main.elf main.hex
      working-directory: ./build
    - name: Program target
      run: $OPEN_OCD_PATH/bin/openocd -f $OPENOCD_PATH/scripts/board/st_nucleo_f4.cfg -c "init; reset halt; flash write_image erase main.hex; reset run; exit"
      working-directory: ./build
